### ISSUE TITLE
Can you add routines to calculate the derivatives of U V and r?

### ISSUE THREAD

**Issue by jamadagni** [ytliu0/ElpMpp02#1]
Hello. I am interested in using this library.

It would be even more useful to me if I could also get the derivatives or speeds in latitude, longitude and distance. However it is not clear to me whether this is straightforward from the paper. I would be interested to hear your feedback on this.

Thanks!

**Comment by ytliu0** [comment]
It's straightforward to calculate the time derivatives. You just need to take the time derivatives of the series. That's what the original FORTRAN code provided by the authors of the ELP/MPP02 does. Each term in the series has the form t^i * sin(arg) or t^i *cos(arg) with i = 0, 1, 2 or 3. Each argument in the sin or cos function is a polynomial in t. So taking the time derivative is straightforard.  I can add that functions later when I have time.

**Comment by ytliu0** [comment]
I've added subroutines in _ElpMpp02.cpp_ to compute the time derivatives. Examples of using the code is added to _example.cpp_.

**Comment by jamadagni** [comment]
Wow so much work so quick! Thanks a lot! I was reading the original Fortran code as you had pointed out by which time you yourself have done it!
