### ISSUE TITLE
Pl provide option to return polar coordinates

### ISSUE THREAD

**Issue by jamadagni** [ytliu0/ElpMpp02#2]
Hello! Right now the routines output rectangular coordinates and you have recently kindly added the provision for outputting derivatives too.

If there were an option to return the polar coordinates themselves rather than compulsorily convert to rectangular, that would be most useful as for many purpose one is interested in polar only as polar is easier to visualize (IMO).

This request applies to both position only and position+velocity functions.

IIANM the algorithm itself originally computes the polar values only, and it's being converted to rectangular before being output, and so that conversion can just be dropped if polar is rqeuired.

It's not necessary to write separate functions but just a flag in the same functions to toggle polar vs rectangular will do.

Thanks!

**Comment by ytliu0** [comment]
The calculation is in the last subroutine of _ElpMpp02.cpp_. You can modify it however you want. The original series are to compute the coordinates in the mean ecliptic of date. If that's what you want, you can simply skip the conversion to rectangular coordinates and the multiplication of precession matrix. If you want the J2000 coordinates, you can simple transform the final rectangular coordinates to the spherical coordinates.

**Comment by hasanelfalakiy** [comment]
> The calculation is in the last subroutine of _ElpMpp02.cpp_. You can modify it however you want. The original series are to compute the coordinates in the mean ecliptic of date. If that's what you want, you can simply skip the conversion to rectangular coordinates and the multiplication of precession matrix. If you want the J2000 coordinates, you can simple transform the final rectangular coordinates to the spherical coordinates.

can you help me?, what is the formula to convert rectangular coordinates such as those generated from NASA's JPL DE (x,y,z) in km to ecliptic and spherical coordinates such as geocentric longitude, geo geo latitude, right ascension hours or degrees, and declination?I'm still confused about the method/formula Please help

**Comment by ytliu0** [comment]
Note that DE's x,y,z are in equatorial coordinates; ELP/MPP02's X,Y,Z are in ecliptic coordinates. They are not the same but related by a rotation matrix.

The rectangular-spherical transformation is
X = r cosV cosU
Y = r sinV cosU
Z = r sinU

r: distance, V: ecliptic longitde/RA, U: ecliptic latitude/Dec

Whether V, U are longitude, latitude or RA,  Dec depends on whether X, Y, Z are in ecliptic coordinates or equatorial coordinates. The inverse transformation is 

r = sqrt(X^2 + Y^2 + Z^2)
V = atan2(Y,X)
U = asin(Z/r)

Note that the distance r is unaffected by rotation. In my code, r and r_dot are calculated and will not be changed by the precession matrix, which is just a rotation matrix. So you don't need to recalculate r and r_dot. For the time derivatives, simply taking the time derivatives of the above equations gives 

V_dot = (X\*Y_dot - Y\*X_dot)/(X^2 + Y^2)
U_dot = (Z_dot - r_dot\*Z/r)/sqrt(X^2+Y^2)

Also note that the X, Y, Z given by DE and ELP/MPP02 are geometric position. More often you want to calculate the apparent position. Then you will have to take the light-travel time and aberration into account: the apparent position at time t is equal to (to high degree of accuracy) the geometric position at t-r/c, where c is the speed of light.

**Comment by hasanelfalakiy** [comment]
> Note that DE's x,y,z are in equatorial coordinates; ELP/MPP02's X,Y,Z are in ecliptic coordinates. They are not the same but related by a rotation matrix.
> 
> The rectangular-spherical transformation is
> X = r cosV cosU
> Y = r sinV cosU
> Z = r sinU
> 
> r: distance, V: ecliptic longitde/RA, U: ecliptic latitude/Dec
> 
> Whether V, U are longitude, latitude or RA,  Dec depends on whether X, Y, Z are in ecliptic coordinates or equatorial coordinates. The inverse transformation is 
> 
> r = sqrt(X^2 + Y^2 + Z^2)
> V = atan2(Y,X)
> U = asin(Z/r)
> 
> Note that the distance r is unaffected by rotation. In my code, r and r_dot are calculated and will not be changed by the precession matrix, which is just a rotation matrix. So you don't need to recalculate r and r_dot. For the time derivatives, simply taking the time derivatives of the above equations gives 
> 
> V_dot = (X\*Y_dot - Y\*X_dot)/(X^2 + Y^2)
> U_dot = (Z_dot - r_dot\*Z/r)/sqrt(X^2+Y^2)
> 
> Also note that the X, Y, Z given by DE and ELP/MPP02 are geometric position. More often you want to calculate the apparent position. Then you will have to take the light-travel time and aberration into account: the apparent position at time t is equal to (to high degree of accuracy) the geometric position at t-r/c, where c is the speed of light.

Thank you in advance for your help, I will try it

**Comment by hasanelfalakiy** [comment]
> Note that DE's x,y,z are in equatorial coordinates; ELP/MPP02's X,Y,Z are in ecliptic coordinates. They are not the same but related by a rotation matrix.
> 
> The rectangular-spherical transformation is
> X = r cosV cosU
> Y = r sinV cosU
> Z = r sinU
> 
> r: distance, V: ecliptic longitde/RA, U: ecliptic latitude/Dec
> 
> Whether V, U are longitude, latitude or RA,  Dec depends on whether X, Y, Z are in ecliptic coordinates or equatorial coordinates. The inverse transformation is 
> 
> r = sqrt(X^2 + Y^2 + Z^2)
> V = atan2(Y,X)
> U = asin(Z/r)
> 
> Note that the distance r is unaffected by rotation. In my code, r and r_dot are calculated and will not be changed by the precession matrix, which is just a rotation matrix. So you don't need to recalculate r and r_dot. For the time derivatives, simply taking the time derivatives of the above equations gives 
> 
> V_dot = (X\*Y_dot - Y\*X_dot)/(X^2 + Y^2)
> U_dot = (Z_dot - r_dot\*Z/r)/sqrt(X^2+Y^2)
> 
> Also note that the X, Y, Z given by DE and ELP/MPP02 are geometric position. More often you want to calculate the apparent position. Then you will have to take the light-travel time and aberration into account: the apparent position at time t is equal to (to high degree of accuracy) the geometric position at t-r/c, where c is the speed of light.

I think I managed to get the ra, dec data for the moon and sun, for the sun I got it from gregmiller's instructions on his website by getting the earth's position from EMB and Moon geocentric data then turn it over, but both ra, dec moon and sun the difference is quite far when compared to vsop87d and elpmpp02,the question is, are the equatorial coordinates presented by JPL DE geocentric or others? is it the same as geometric == geocentric?I use gmiller's java program code here: https://github.com/gmiller123456/jpl-development-ephemeris/tree/master/Binary/Java
and my JPL DE binary files use DE405 binary
I followed the instructions on gmiller's website: https://www.celestialprogramming.com/jpl-ephemeris-format/jpl-ephemeris-format.html

**Comment by ytliu0** [comment]
>  is it the same as geometric == geocentric?

No, geometric and geocentric don't mean the same thing. 

> I use gmiller's java program code here: https://github.com/gmiller123456/jpl-development-ephemeris/tree/master/Binary/Java
and my JPL DE binary files use DE405 binary
I followed the instructions on gmiller's website: https://www.celestialprogramming.com/jpl-ephemeris-format/jpl-ephemeris-format.html

I'm not familiar with their code. Why don't you post your question there?

The original issue is resolved. It's now getting off topic. Closing now.

**Comment by hasanelfalakiy** [comment]
> >  is it the same as geometric == geocentric?
> 
> No, geometric and geocentric don't mean the same thing. 
> 
> > I use gmiller's java program code here: https://github.com/gmiller123456/jpl-development-ephemeris/tree/master/Binary/Java
> and my JPL DE binary files use DE405 binary
> I followed the instructions on gmiller's website: https://www.celestialprogramming.com/jpl-ephemeris-format/jpl-ephemeris-format.html
> 
> I'm not familiar with their code. Why don't you post your question there?
> 
> The original issue is resolved. It's now getting off topic. Closing now.
> 

I have asked the owner of the code but he is reluctant to answer, so I am looking for other help
