### ISSUE TITLE
Source of cosine switch?

### ISSUE THREAD

**Issue by jamadagni** [ytliu0/ElpMpp02#3]
https://github.com/ytliu0/ElpMpp02/blob/b993b8c23d879ece0749c7c46840ed70aa4887d4/ElpMpp02.cpp#L410-L414

Hello. I notice that you have switched to cosine to compute the distance. However I don't seem to find any reference to this in either the 2003 paper or the Fortran code where only sine is seen. Am I missing something? Please clarify. Thanks.

**Comment by ytliu0** [comment]
Distance is the cosine series. Read the pdf documentation provided by the authors accompanying with their FORTRAN source code. I also mention it in my own documentation.

**Comment by jamadagni** [comment]
Yes thanks I saw that, but still, I don't see the original paper of 2003 mentioning cosine, and I don't see it in the original Fortran code (lines 692-714):

```fortran
! --- Evaluation of the series: substitution of time in the series -----
!     Variable iv=1 : Longitude
!     Variable iv=2 : Latitude
!     Variable iv=3 : Distance
!
      do iv=1,3
!
         v(iv)=0.d0
         v(iv+3)=0.d0
!
! ------ Main Problem series -------------------------------------------
!
         do n=nmpb(iv,2),nmpb(iv,3)
            x=cmpb(n)
            y=fmpb(0,n)
            yp=0.d0
            do k=1,4
               y=y+fmpb(k,n)*t(k)
               yp=yp+k*fmpb(k,n)*t(k-1)
            enddo
            v(iv)=v(iv)+x*sin(y)
            v(iv+3)=v(iv+3)+x*yp*cos(y)
         enddo
```

That cosine is for the derivative and not the position value, so that's not the answer.

However the test output of your code and the original Fortran seems to be comparable.

I still wonder what I am missing. :disappointed: 

(Sorry for the repeated messages…)

**Comment by ytliu0** [comment]
To me, their FORTRAN code is kind of messy. There are a few places I have to go though the code carefully to figure out their logic.

As to your question, I think the secret is in line 790:
```
!
! --- Reading Main Problem series --------------------------------------
!
      ir=0
      do iv=1,3
      do k=1,3
         nmpb(iv,k)=0
      enddo
      enddo
!
      do iv=1,3
         open (lu,file=filename(iv),status='old',iostat=nerr)
         if (nerr.ne.0) return
         read (lu,1001,iostat=nerr,end=100) nmpb(iv,1)
         if (nerr.ne.0) return
         nmpb(iv,2)=ir+1
         nmpb(iv,3)=nmpb(iv,1)+nmpb(iv,2)-1
         do n=1,nmpb(iv,1)
            read (lu,1002,iostat=nerr,end=100) ilu,a,b
            if (nerr.ne.0) return
            ir=ir+1
            tgv=b(1)+dtasm*b(5)
            if (iv.eq.3) a=a-2.d0*a*delnu/3.d0
            cmpb(ir) = a+tgv*(delnp-am*delnu)
     &               + b(2)*delg + b(3)*dele + b(4)*delep
            do k=0,4
               fmpb(k,ir)=0.d0
               do i=1,4
                  fmpb(k,ir)=fmpb(k,ir)+ilu(i)*del(i,k)
               enddo
            enddo
            if (iv.eq.3) fmpb(0,ir)=fmpb(0,ir)+pis2 
         enddo
         close (lu)
      enddo
!
```
Notice the line "**if (iv.eq.3) fmpb(0,ir)=fmpb(0,ir)+pis2**"

They add pi/2 to the phases for distance, that's why they can use sine for distance as sin(x+pi/2) = cos(x).

**Comment by jamadagni** [comment]
Wow yes that's right! I hadn't thought to check in the loading procedure. Great find! 

This would make coding simpler by reducing clutter I guess. This way you don't need to write a separate for-loop, or the derivative as −sin.

**Comment by ytliu0** [comment]
Yes, that would make the code simpler. But I'm thinking in terms of computational efficiency. There are thousands of terms in the main series, so the if-statement has to be executed thousands of times there. By placing the if-statement outside the loop, it saves the execution time although the time saved may be too little to really mater.

**Comment by jamadagni** [comment]
But if you do as they did and add τ÷4 to the phases themselves, then you don't even need the if branch…

**Comment by ytliu0** [comment]
Unlike the perturbation series, the main series don't have initial phases in the data file. The authors compute the coefficients for the amplitudes and phases for the whole series in powers of t from the data files in the initial setup. That's why they can add pi/2 there. That's the advantage of their approach, but it adds an overhead in the initial setup. 

You can modify the code to minic the authors' original code if you like their approach better, or you can simple use their code.

**Comment by jamadagni** [comment]
Thanks for your reply.
